CREATE TABLE `demo`.`pano_images` (
  `ID` INT UNSIGNED NOT NULL COMMENT '图像ID\n和pano网站上的ID一致',
  `LAT` DOUBLE NOT NULL,
  `LNG` DOUBLE NOT NULL,
  `URL` VARCHAR(45) NOT NULL COMMENT 'the url of images in file system',
  `LOCATION` VARCHAR(45) NULL COMMENT '图像的大致位置',
  `TITLE` VARCHAR(45) NULL COMMENT '图像的标题',
  `TAG` VARCHAR(45) NULL COMMENT '标签',
  `CAMERA` VARCHAR(45) NULL COMMENT '相机信息',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `LAT_INDEX` (`LAT` ASC),
  INDEX `LNG_INDEX` (`LNG` ASC));
